# pin clang<18 because cppyy (and cling) need an old enough libcxx, see
# https://github.com/conda-forge/cppyy-feedstock/blob/main/recipe/meta.yaml
c_compiler_version:        # [osx]
  - 17                     # [osx]
cxx_compiler_version:      # [osx]
  - 17                     # [osx]
# Many versions of SageMath are built against FLINT 2. Recent versions are
# built against 3.0. To make e-antic compatible with versions of SageMath >=10
# (for downstream testing) we built against several releases of FLINT (and not
# just the latest from the pinning feedstock.)
libflint:
  - '2.9'
  - '3.0'
  - '3.1'
  - '3.2'
