{% set name = "E-ANTIC" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatsurf/e-antic/releases/download/{{ version }}/e-antic-{{ version }}.tar.gz
  sha256: 9ae24ffd55b3046c6db5af253574c1ee734751f20ceb2f123b47f69fac031f31

build:
  number: 1

outputs:
  - name: e-antic
    script: build-libeantic.sh  # [not win]
    script: bld-libeantic.bat  # [win]
    run_exports:
      # e-antic uses semantic versioning https://github.com/videlec/e-antic/issues/12
      - {{ pin_subpackage("e-antic") }}
    requirements:
      build:
        - libtool   # [unix]
        - automake  # [unix]
        - make      # [unix]
        - autotools_clang_conda  # [win]
        - gnuconfig  # [unix]
        - {{ compiler('cxx') }}
      host:
        - antic
        - boost-cpp
        - gmp       # [unix]
        - mpir      # [win]
        - arb
        - libflint
    test:
      commands:
        - test -f $PREFIX/include/e-antic/e-antic.h  # [linux or osx]
        - test -f $PREFIX/lib/libeantic.so           # [linux]
        - test -f $PREFIX/lib/libeanticxx.so         # [linux]
        - test -f $PREFIX/lib/libeantic.dylib        # [osx]
        - test -f $PREFIX/lib/libeanticxx.dylib      # [osx]
  - name: pyeantic
    script: build-pyeantic.sh  # [not win]
    script: bld-pyeantic.bat  # [win]
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - libtool   # [unix]
        - automake  # [unix]
        - make      # [unix]
        - autotools_clang_conda  # [win]
        - gnuconfig  # [unix]
        - {{ compiler('cxx') }}
      host:
        - boost-cpp
        - python
        - cppyy
        - cppyythonizations
        - setuptools
        - pytest
        - {{ pin_subpackage("e-antic") }}
      run:
        - boost-cpp
        - python
        - cppyy
        - cppyythonizations
        # A subpackage does not see the run_exports of another subpackage:
        # https://github.com/conda/conda-build/issues/3478
        - {{ pin_subpackage("e-antic") }}
    test:
      imports:
        - pyeantic

about:
  home: https://github.com/flatsurf/e-antic
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: embedded algebraic number fields
  description: |
    E-ANTIC is a C/C++ library to deal with real embedded number fields built
    on top of ANTIC. Its aim is to have as fast as possible exact arithmetic
    operations and comparisons.
  dev_url: https://github.com/videlec/e-antic

extra:
  recipe-maintainers:
    - saraedum
    - videlec
