{% set name = "E-ANTIC" %}
{% set version = environ.get('GIT_DESCRIBE_TAG')|string %}
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set build_string = "master_" + build_number %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/videlec/e-antic.git
  git_rev: 1edca4ed9c88cb39037066f0e51c04073948e49a

build:
  number: {{ build_number }}
  string: {{ build_string }}
  # dependencies libflint and arb are not available for Windows on conda-forge
  skip: True  # [win]
  # compiler(cxx) is clang4 on OSX which lacks some C++ features
  skip: True  # [osx]
  run_exports:
  # e-antic uses semantic versioning https://github.com/videlec/e-antic/issues/12
  - {{ pin_subpackage("e-antic") }}


requirements:
  build:
    - libtool
    - automake
    - {{ compiler('cxx') }}
  host:
    # E-ANTIC depends on antic; since antic has never been released officially
    # (https://github.com/wbhart/antic/issues/31,) E-ANTIC ships the relevant
    # parts of ANTIC.
    # - antic
    - boost-cpp
    - gmp
    - arb
    - libflint 2.5.*

test:
  commands:
    - test -f $PREFIX/include/e-antic/e-antic.h  # [linux or osx]
    - test -f $PREFIX/lib/libeantic.so           # [linux]
    - test -f $PREFIX/lib/libeanticxx.so         # [linux]
    - test -f $PREFIX/lib/libeantic.dylib        # [osx]
    - test -f $PREFIX/lib/libeanticxx.dylib      # [osx]

about:
  home: https://github.com/videlec/e-antic
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'embedded algebraic number fields'
  description: |
    E-ANTIC is a C/C++ library to deal with real embedded number fields built
    on top of ANTIC. Its aim is to have as fast as possible exact arithmetic
    operations and comparisons.
  dev_url: https://github.com/videlec/e-antic

extra:
  recipe-maintainers:
    - saraedum
    - videlec
