{% set name = "e-antic" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatsurf/e-antic/releases/download/{{ version }}/e-antic-{{ version }}.tar.gz
  sha256: eea1dc66fed5962425bc7d2c5ccecb50d25c082b1d84276fa3838bfa96d9cb62

build:
  number: 4
  # Upstream doesn't support MSVC yet.
  skip: true  # [win]

outputs:
  - name: libeantic
    script: build-libeantic.sh
    run_exports:
      # e-antic uses semantic versioning https://github.com/videlec/e-antic/issues/12
      - {{ pin_subpackage("libeantic") }}
    requirements:
      build:
        - libtool   # [unix]
        - automake  # [unix]
        - make      # [unix]
        - autotools_clang_conda  # [win]
        - gnuconfig  # [unix]
        - {{ compiler('cxx') }}
      host:
        - antic
        - boost-cpp
        - gmp       # [unix]
        - mpir      # [win]
        - arb
        - libflint
    test:
      commands:
        - test -f $PREFIX/include/e-antic/e-antic.h  # [linux or osx]
        - test -f $PREFIX/lib/libeantic.so           # [linux]
        - test -f $PREFIX/lib/libeanticxx.so         # [linux]
        - test -f $PREFIX/lib/libeantic.dylib        # [osx]
        - test -f $PREFIX/lib/libeanticxx.dylib      # [osx]
  - name: pyeantic
    script: build-pyeantic.sh
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - libtool   # [unix]
        - automake  # [unix]
        - make      # [unix]
        - autotools_clang_conda  # [win]
        - gnuconfig  # [unix]
        - {{ compiler('cxx') }}
      host:
        - boost-cpp
        - python
        - cppyy
        - cppyythonizations
        - setuptools
        - pytest
        - {{ pin_subpackage("libeantic") }}
      run:
        - boost-cpp
        - python
        - cppyy
        - cppyythonizations
        # Pin cysignals, see https://github.com/flatsurf/e-antic/issues/223
        - cysignals <1.11.0  # [osx]
        # A subpackage does not see the run_exports of another subpackage:
        # https://github.com/conda/conda-build/issues/3478
        - {{ pin_subpackage("libeantic") }}
    test:
      imports:
        - pyeantic

about:
  home: https://github.com/flatsurf/e-antic
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: embedded algebraic number fields
  description: |
    e-antic is a C/C++/Python library to deal with real embedded number fields
    built on top of ANTIC. It aims to provide the fastest possible exact
    arithmetic operations and comparisons.
  dev_url: https://github.com/flatsurf/e-antic

extra:
  recipe-maintainers:
    - saraedum
    - videlec
