{% set name = "e-antic" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatsurf/e-antic/releases/download/{{ version }}/e-antic-{{ version }}.tar.gz
  sha256: 8328e6490129dfec7f4aa478ebd54dc07686bd5e5e7f5f30dcf20c0f11b67f60

build:
  number: 0
  # Upstream doesn't support MSVC yet.
  skip: true  # [win]

outputs:
  - name: libeantic
    script: build-libeantic.sh
    run_exports:
      # e-antic uses semantic versioning https://github.com/videlec/e-antic/issues/12
      - {{ pin_subpackage("libeantic") }}
    requirements:
      build:
        - libtool   # [unix]
        - automake  # [unix]
        - make      # [unix]
        - autotools_clang_conda  # [win]
        - gnuconfig  # [unix]
        - {{ compiler('cxx') }}
      host:
        # We only need the libboost-headers at compile time. However, since we
        # use bits of boost in our API, code built against libeantic must be
        # built with a compatible version of the headers. Therefore, we add a
        # liboost pin to our run exports so libboost-headers are going to be
        # in a compatible version.
        - libboost-devel
        - gmp       # [unix]
        - mpir      # [win]
        - libflint
    test:
      commands:
        - test -f $PREFIX/include/e-antic/e-antic.h  # [linux or osx]
        - test -f $PREFIX/lib/libeantic.so           # [linux]
        - test -f $PREFIX/lib/libeanticxx.so         # [linux]
        - test -f $PREFIX/lib/libeantic.dylib        # [osx]
        - test -f $PREFIX/lib/libeanticxx.dylib      # [osx]

  - name: pyeantic
    script: build-pyeantic.sh
    build:
      # cppyy is not available on ppc64le
      skip: true  # [ppc64le]
      # cppyy is not available on aarch64
      skip: true  # [aarch64]
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - libtool   # [unix]
        - automake  # [unix]
        - make      # [unix]
        - autotools_clang_conda  # [win]
        - gnuconfig  # [unix]
        - {{ compiler('cxx') }}
      host:
        # Note that the libboost-devel from libeantic forces these headers to be
        # compatible with ones used when building libeantic.
        - libboost-headers
        - python
        - cppyy
        - cppyythonizations
        - gmpxxyy
        - setuptools
        - pytest
        - {{ pin_subpackage("libeantic") }}
      run:
        - python
        - cppyy
        - cppyythonizations
        - gmpxxyy
        # cppyy dynamically compiles C++ wrappers at runtime, therefore we need C++ headers of boost.
        # Note that the libboost-devel from libeantic forces these headers to be
        # compatible with ones used when building libeantic.
        - libboost-headers
        # A subpackage does not see the run_exports of another subpackage:
        # https://github.com/conda/conda-build/issues/3478
        - {{ pin_subpackage("libeantic") }}
    test:
      imports:
        - pyeantic

about:
  home: https://github.com/flatsurf/e-antic
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: embedded algebraic number fields
  description: |
    e-antic is a C/C++/Python library to deal with real embedded number fields
    built on top of ANTIC. It aims to provide the fastest possible exact
    arithmetic operations and comparisons.
  dev_url: https://github.com/flatsurf/e-antic

extra:
  recipe-maintainers:
    - saraedum
    - videlec
