{% set name = "E-ANTIC" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.labri.fr/perso/vdelecro/{{ name | lower }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: d935ebaa59fcc6742fa62813f7039def52011f65ce3ed08f2da6ce66224f9859

build:
  number: 1
  # dependencies libflint and arb are not available for Windows on conda-forge
  skip: true  # [win]
  run_exports:
  # e-antic uses semantic versioning https://github.com/videlec/e-antic/issues/12
    - {{ pin_subpackage("e-antic") }}


requirements:
  build:
    - libtool
    - automake
    - make
    - {{ compiler('cxx') }}
  host:
    # E-ANTIC depends on antic; since antic has never been released officially
    # (https://github.com/wbhart/antic/issues/31,) E-ANTIC ships the relevant
    # parts of ANTIC.
    # - antic
    - gmp
    - arb
    - libflint

test:
  commands:
    - test -f $PREFIX/include/e-antic/e-antic.h  # [linux or osx]
    - test -f $PREFIX/lib/libeantic.so           # [linux]
    - test -f $PREFIX/lib/libeanticxx.so         # [linux]
    - test -f $PREFIX/lib/libeantic.dylib        # [osx]
    - test -f $PREFIX/lib/libeanticxx.dylib      # [osx]

about:
  home: https://github.com/videlec/e-antic
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: embedded algebraic number fields
  description: |
    E-ANTIC is a C/C++ library to deal with real embedded number fields built
    on top of ANTIC. Its aim is to have as fast as possible exact arithmetic
    operations and comparisons.
  dev_url: https://github.com/videlec/e-antic

extra:
  recipe-maintainers:
    - saraedum
    - videlec
