{% set name = "E-ANTIC" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.labri.fr/perso/vdelecro/{{ name | lower }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: f73dad444fd81422d9a1594668615da94405fb6428ce8f2535b58f4cfe88a72d

build:
  number: 0
  # Upstream doesn't support MSVC yet.
  skip: true  # [win]
  run_exports:
  # e-antic uses semantic versioning https://github.com/videlec/e-antic/issues/12
    - {{ pin_subpackage("e-antic") }}


requirements:
  build:
    - libtool   # [unix]
    - automake  # [unix]
    - make      # [unix]
    - autotools_clang_conda  # [win]
    - {{ compiler('cxx') }}
  host:
    # E-ANTIC depends on antic; since antic has never been released officially
    # (https://github.com/wbhart/antic/issues/31,) E-ANTIC ships the relevant
    # parts of ANTIC.
    # - antic
    - gmp       # [unix]
    - mpir      # [win]
    - arb
    - libflint

test:
  commands:
    - test -f $PREFIX/include/e-antic/e-antic.h  # [linux or osx]
    - test -f $PREFIX/lib/libeantic.so           # [linux]
    - test -f $PREFIX/lib/libeanticxx.so         # [linux]
    - test -f $PREFIX/lib/libeantic.dylib        # [osx]
    - test -f $PREFIX/lib/libeanticxx.dylib      # [osx]

about:
  home: https://github.com/videlec/e-antic
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: embedded algebraic number fields
  description: |
    E-ANTIC is a C/C++ library to deal with real embedded number fields built
    on top of ANTIC. Its aim is to have as fast as possible exact arithmetic
    operations and comparisons.
  dev_url: https://github.com/videlec/e-antic

extra:
  recipe-maintainers:
    - saraedum
    - videlec
