{% set name = "E-ANTIC" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatsurf/e-antic/releases/download/{{ version }}/e-antic-{{ version }}.tar.gz
  sha256: 8302e9d7fca4b33b1a2fd8ed88df6548d55c54694f428606e87bf8c6f129b317

build:
  number: 0
  # Upstream doesn't support MSVC yet.
  skip: true  # [win]
  run_exports:
  # e-antic uses semantic versioning https://github.com/videlec/e-antic/issues/12
    - {{ pin_subpackage("e-antic") }}


requirements:
  build:
    - libtool   # [unix]
    - automake  # [unix]
    - make      # [unix]
    - autotools_clang_conda  # [win]
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
  host:
    - antic
    - gmp       # [unix]
    - mpir      # [win]
    - arb
    - libflint

test:
  commands:
    - test -f $PREFIX/include/e-antic/e-antic.h  # [linux or osx]
    - test -f $PREFIX/lib/libeantic.so           # [linux]
    - test -f $PREFIX/lib/libeanticxx.so         # [linux]
    - test -f $PREFIX/lib/libeantic.dylib        # [osx]
    - test -f $PREFIX/lib/libeanticxx.dylib      # [osx]

about:
  home: https://github.com/flatsurf/e-antic
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: embedded algebraic number fields
  description: |
    E-ANTIC is a C/C++ library to deal with real embedded number fields built
    on top of ANTIC. Its aim is to have as fast as possible exact arithmetic
    operations and comparisons.
  dev_url: https://github.com/videlec/e-antic

extra:
  recipe-maintainers:
    - saraedum
    - videlec
